
ALTER TABLE treatment ADD COLUMN durationInMin INT NOT NULL;
ALTER TABLE treatment ADD COLUMN aboutClient VARCHAR(1024) NOT NULL;
ALTER TABLE treatment ADD COLUMN aboutTreatment VARCHAR(1024) NOT NULL;
ALTER TABLE treatment ADD COLUMN aboutHomework VARCHAR(1024) NOT NULL;
