
ALTER TABLE CLIENT ADD COLUMN hobbies VARCHAR(512) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN origin  VARCHAR(512) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN tcmNote VARCHAR(5120) DEFAULT '' NOT NULL;

-- textImpression textMedical textComplaints textPersonal textObjective
ALTER TABLE CLIENT ADD COLUMN textImpression VARCHAR(5120) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN textMedical VARCHAR(5120) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN textComplaints VARCHAR(5120) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN textPersonal VARCHAR(5120) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN textObjective VARCHAR(5120) DEFAULT '' NOT NULL;
