
ALTER TABLE CLIENT ADD COLUMN hobbies VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN origin  VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE CLIENT ADD COLUMN tcmNote VARCHAR(1024) DEFAULT '' NOT NULL;
